# 服务配置
server:
  port: 8085
# spring配置
spring:
  # 数据源配置
  datasource:
    # 动态数据源
    dynamic:
      primary: demo
      strict: true
      datasource:
        demo:
          url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: 123456
    # 数据库连接池

  # servlet配置
  servlet:
    multipart:
      # 文件最大请求
      max-file-size: 1000MB
      # 数据最大请求
      max-request-size: 1000MB
# mybatis-plus配置
mybatis-plus:
  configuration:
    # 日志
#    log-impl: com.dhp.common.core.mybatis.MyBaitsLogConfig
    map-underscore-to-camel-case: true
    auto-mapping-unknown-column-behavior: WARNING
    call-setters-on-nulls: false
    cache-enabled: false
  mapper-locations:
    - classpath*:/mapper/**/*.xml
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

  typeEnumsPackage: com.cbz.model.enums
# api文档配置
knife4j:
  enable: true

# 系统日志
logging:
  config: classpath:logback-dev.xml


# 自定义应用属性
application:
  # swagger 开关
  swagger:
    enable: true
  message:
    cpId: http123